### ISSUE TITLE
Match "Latest" tag on Docker Hub w/ Main Ubuntu Image Behavior

### ISSUE THREAD

**Issue by edm00se** [umiddelb/armhf-ubuntu#3]
If you're looking to follow closely to the behavior of the main `ubuntu` image in Docker Hub, they tag the "latest" as latest LTS release; right now that's 16.04.

Currently the "latest" for `armv7/armhf-ubuntu` on Docker Hub points to 16.10.

Thanks for the work in the arm space, it's pretty handy.

**Comment by umiddelb** [comment]
Sorry, I don't have the time to maintain these images any more, while there are plenty of alternatives and really official armv7 images available in the meantime.
